### 聚合操作

In [2]:
import numpy as np
L = np.random.random(100)

In [3]:
L

array([ 0.27719707,  0.87028361,  0.68087482,  0.36350269,  0.93588324,
        0.07227126,  0.41099436,  0.5831046 ,  0.53901486,  0.27592838,
        0.51595701,  0.96936183,  0.66920521,  0.13671439,  0.52362834,
        0.67138901,  0.88361643,  0.74826082,  0.12591031,  0.54486902,
        0.08103602,  0.11870965,  0.46818924,  0.61799307,  0.56808969,
        0.51533916,  0.18985689,  0.06242253,  0.73625681,  0.90085777,
        0.68944669,  0.16266884,  0.9938263 ,  0.95117218,  0.59339638,
        0.56837707,  0.2194519 ,  0.46698108,  0.16433387,  0.54307203,
        0.30586405,  0.81074292,  0.64536554,  0.95628712,  0.29000746,
        0.29032901,  0.20274641,  0.58738925,  0.33888907,  0.36226127,
        0.40062493,  0.35920568,  0.50802039,  0.06456239,  0.64146383,
        0.26973706,  0.27192018,  0.09471337,  0.80355724,  0.74427644,
        0.61560097,  0.4186799 ,  0.78459998,  0.89258729,  0.12841704,
        0.32829542,  0.45228451,  0.17899469,  0.41429223,  0.84

In [5]:
sum(L)

48.647037910133875

In [7]:
np.sum(L)

48.647037910133868

In [9]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

153 ms ± 2.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
945 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
np.min(big_array)

3.77585661126556e-06

In [13]:
np.max(big_array)

0.99999946497580461

In [14]:
big_array.min()

3.77585661126556e-06

In [15]:
big_array.max()

0.99999946497580461

In [17]:
big_array.sum()

500141.8417188715

In [19]:
X = np.arange(16).reshape(4,-1)

In [20]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.sum(X)

120

In [23]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [25]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [27]:
np.prod(X)

0

In [29]:
np.prod(X + 1)

2004189184

In [31]:
np.mean(X)

7.5

In [33]:
np.median(X)

7.5

In [36]:
big_array

array([ 0.64157145,  0.84829137,  0.02776446, ...,  0.31441029,
        0.70460694,  0.49106915])

In [38]:
np.percentile(big_array,q=50)

0.50059381015417159

In [40]:
np.percentile(big_array,q=100)

0.99999946497580461

In [41]:
np.max(big_array)

0.99999946497580461

In [46]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array,q=percent))

3.77585661127e-06
0.250111745709
0.500593810154
0.750212045777
0.999999464976


In [48]:
np.var(big_array)

0.083289663175939749

In [50]:
np.std(big_array)

0.2885994857513432

In [51]:
x = np.random.normal(0,1,size=100000)

### 索引

In [53]:
np.min(x)

-4.5279279465728859

In [54]:
np.argmin(x)

12427

In [56]:
x[12427]

-4.5279279465728859

In [58]:
np.argmax(x)

35384

In [61]:
x[35384]

3.8415423557580461

### 排序和使用索引

In [64]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
np.random.shuffle(x)
x

array([ 1,  3,  8,  7,  4, 14, 13,  6,  0,  5,  9, 10, 15, 12,  2, 11])

In [67]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
x

array([ 1,  3,  8,  7,  4, 14, 13,  6,  0,  5,  9, 10, 15, 12,  2, 11])

In [70]:
x.sort()

In [71]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
X = np.random.randint(10,size=(4,4))
X

array([[4, 2, 7, 7],
       [9, 5, 6, 3],
       [3, 6, 8, 2],
       [4, 0, 8, 6]])

In [73]:
np.sort(X)

array([[2, 4, 7, 7],
       [3, 5, 6, 9],
       [2, 3, 6, 8],
       [0, 4, 6, 8]])

In [74]:
np.sort(X,axis=0)

array([[3, 0, 6, 2],
       [4, 2, 7, 3],
       [4, 5, 8, 6],
       [9, 6, 8, 7]])

In [75]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [76]:
np.random.shuffle(x)

In [77]:
x

array([ 4,  6, 15,  8, 14, 13,  9,  5, 11,  0,  7, 12, 10,  3,  1,  2])

In [79]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4, 13,  9,  6, 11, 14,  7, 12, 10,  8, 15,  5])

In [82]:
np.argpartition(x, 3)

array([14,  9, 15, 13,  0,  5,  6,  1,  8,  4, 10, 11, 12,  3,  2,  7], dtype=int64)

In [83]:
X

array([[4, 2, 7, 7],
       [9, 5, 6, 3],
       [3, 6, 8, 2],
       [4, 0, 8, 6]])

In [84]:
np.argsort(X,axis=1)

array([[1, 0, 2, 3],
       [3, 1, 2, 0],
       [3, 0, 1, 2],
       [1, 0, 3, 2]], dtype=int64)