In [1]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [4]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2]

array([3, 5, 7])

In [8]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [9]:
ind = [3,5,8]

In [10]:
x[ind]

array([3, 5, 8])

In [14]:
ind = np.array([[0,2],[1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [18]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [22]:
X[0,col]

array([1, 2, 3])

In [24]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [25]:
col = [True,False,True,True]

In [27]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较

In [28]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [31]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [32]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [34]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [35]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [36]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [37]:
2 * x == 24 -4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [38]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [39]:
np.sum(x<=3)

4

In [41]:
np.count_nonzero(x<=3)

4

In [42]:
np.any(x == 0)

True

In [43]:
np.any(x<0)

SyntaxError: invalid syntax (<ipython-input-43-c82933546f78>, line 1)

In [44]:
np.all(x >= 0)

True

In [45]:
np.all(x > 0)

False

In [46]:
X 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.sum(X % 2 == 0)

8

In [48]:
np.sum(X%2 == 0, axis = 1)

array([2, 2, 2, 2])

In [49]:
np.sum(X%2 == 0, axis=0)

array([4, 0, 4, 0])

In [51]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [52]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
np.sum((x > 3) & (x < 10))

6

In [54]:
x[x<5]

array([0, 1, 2, 3, 4])

In [55]:
x[x%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])